### ISSUE TITLE
[BUG] - Astroid V3 refused to connect

### ISSUE THREAD

**Issue by theshmunguss1** [RamWorks-Development-Group/RamHub#12]
**Describe the bug**
Astroid V3 does not work.

**To Reproduce**
1. Open Astroid via the taskbar.

**Expected behavior**
Astroid opens.

**Screenshots**
![Screenshot 2024-05-08 11 07 03 AM](https://github.com/RamWorks-Development-Group/RamHub/assets/142841882/c70632fd-58d3-4a1b-96d3-4bc90d2f6155)

**Comment by YesTheProxy** [comment]
it's doing that on all rps computers but, not home computers

**Comment by DJshelfmushroom** [comment]
did you mean to make this on ram os or smthn?

**Comment by YesTheProxy** [comment]
yeah he did

**Comment by theshmunguss1** [comment]
> did you mean to make this on ram os or smthn?

Yeah. I was in a rush and accidentally opened this repository.

**Comment by DJshelfmushroom** [comment]
Can't reproduce not at school, probably IP banned

**Comment by theshmunguss1** [comment]
Back up now. It's working.
